- app/Http/Controllers/IndexController.php
- resources/views/core/header.blade.php
Merge after #43 (would rebase but I have to teach lab soon) 
Send TAs to the TA Console instead of a check in page
> Redirect TA page

- resources/views/core/footer.blade.php
> Add analytics tracking code

- app/Http/Controllers/IndexController.php
Handle and throw nice warning when a user denies access to OK account.
> Gracefully handle OAuth access denied error

- app/Feedback.php
- app/Http/Controllers/TAController.php
- app/Http/routes.php
- resources/views/ta/console.blade.php
Signed off by Colin Schoen <cschoen@berkeley.edu>
> Add feedback

- app/Http/Controllers/IndexController.php
> Use url oauth

- app/Http/Controllers/DevController.php
- app/Http/Kernel.php
- app/Http/Middleware/Dev.php
- app/Http/routes.php
Add dev login functionality in local environment
> Add dev login functionality

- app/Http/Controllers/DevController.php
- app/Http/Kernel.php
- app/Http/Middleware/Dev.php
- app/Http/routes.php
* Add dev controller
* Add dev login functionality
> Add dev login functionality (#93)

- app/Http/Controllers/TAController.php
- app/Http/routes.php
- resources/views/ta/console.blade.php
> Implement editing checkins

- resources/views/ta/console.blade.php
> Fix JS error blocking tutors from editing checkins

- composer.json
> Add post-deploy-cmd

- app.yaml
- composer.json
> Add app.yaml and include php requirement.

- app/Http/Controllers/LabAssistantController.php
> No unit restrictions

- resources/views/core/header.blade.php
> Load Google Fonts over HTTPS

- README.md
- resources/views/core/header.blade.php
> Merge in Master

- README.md
> Fix migration commands in deploy instructions

- resources/views/emails/checkin.blade.php
- resources/views/emails/reset.blade.php
> Stop hard coding class name and url

- README.md
> Fix local domain in README.md

- app/Http/Controllers/LabAssistantController.php
- app/Http/routes.php
- resources/views/core/header.blade.php
> Add solutions link to navbar

- app/Http/Controllers/TAController.php
> Load users route by default in TA Console

- resources/views/assignments.blade.php
> 2.5 -> 3 hours per unit

- resources/views/core/header.blade.php
> Fix header link

- app/Http/Controllers/TAController.php
> Fix announcement redirect url

- app/Http/Controllers/TAController.php
- resources/views/ta/modules/checkins.blade.php
- resources/views/ta/modules/users.blade.php
> Fix issue with edit check in modal

- app/Http/Controllers/TAController.php
- app/Http/routes.php
- public/css/custom.css
- resources/views/ta/modules/users.blade.php
- resources/views/ta/modules/users/user.blade.php
Adds user page and ability to swap section assignments, remove section assignments and update user information.
> Adds new user page

- public/css/custom.css
- resources/views/ta/modules/checkins.blade.php
> Make checkin actions more visible.

- resources/views/ta/modules/sections.blade.php
> Move section actions to left of table for easier finding

- resources/views/core/footer.blade.php
- resources/views/information.blade.php
> Update credits and github button

- resources/views/core/footer.blade.php
- resources/views/core/header.blade.php
- resources/views/la/checkin.blade.php
> Add type to search for GSI

- app.json
> Add app.json for postdeploy hook

- README.md
> Add missing dev environment instructions to readme

- app/Http/Controllers/TAController.php
> Add user hours and units to roster CSV export

- app/Http/Controllers/LabAssistantController.php
> Don't enforce hours cap for CS61B

- resources/views/core/footer.blade.php
> Change jQuery CDN to CloudFlare to fix certificate validation issues

- README.md
Adds APP_URL env variable to documentation.
> Include missing env variable in documentation

- app/Http/Controllers/IndexController.php
> Gives instructors staff access on OAuth login

- app/Http/Controllers/LabAssistantController.php
Changed the subject line for the checkin email to Lab Assistants from "CS61A" to "Data 8".
> Changed the header of the email from CS61A to Data 8

- resources/views/core/footer.blade.php
> Kill Google Analytics
